### ISSUE TITLE
Spin-candidate class and GitHub sync

### ISSUE THREAD

**Issue by chargio** [miq-consumption/manageiq-galaxy#52]
Spins are based on repos.

Currently we are importing directly the repos that are suitable to be Spins into Galaxy.

1. The user press refresh
2. The system reviews all the repos in the user profile and start processing them.
3. Those repos that have a .manageiq-spin file in the root folder are considered spins and are imported as SpinCandidate. There is no more tests or metadata management in this phase.

The user can ask for the spin to be published. In that moment:
1. All the tests are run:
  - [ ] /.manageiq-spin has to be present
  - [ ] /metadata.yml has to be present and have the right format
  - [ ] There must be a license associated
  - [ ] There must be a Readme
  - [ ] There must be a Release at least

The results of the tests will be stored in the SpinCandidate, and can be shown to the customer.

If all those tests pass, a Spin will be created or updated with the data.

**Comment by aljesusg** [comment]
Just merged
